version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    
    volumes: 
      - currency-data:/var/lib/mysql
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    container_name: ${MYSQL_HOST}
    
    ports:
      - ${MYSQL_PORT_IN_DOCKER}

    volumes:
      - currency-data:/var/lib/mysql
      
volumes:
  currency-data:
